sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t javicabanas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true javicabanas/docker-react npm run test